


    <header class="header-logo">
    	<img src="/img/logo.png" class="img-fluid">
      <div class="container text-center">
        <!--<h1>Join the Game</h1>-->
        <!--<p class="lead">a simulated horse club for the mature enthusiast</p>-->
      </div>
    </header>


    <!-- Page Content -->
    <div class="container">

<br/>


      <!-- Features Section -->
      <div class="row">
        <div class="col-lg-12">
          <h2>Terms of Service</h2>September 20, 2020<BR>


<p>Please review our Terms of Service thoroughly. By accessing and or using our services (which are defined below), you agree to be bound by these Terms of Service and all terms incorporated by reference. If you do not agree to these terms of service, do not access or use our services. <BR><BR>These Terms of Service ("Terms") apply to your access to and the use of our website. These Terms do not alter in any way the terms or conditions of any other agreement you may have with us or our subsidiaries or affiliates, for products, services or otherwise.<BR><BR>We reserve the right to change or modify these Terms at any time and in our sole discretion. If changes are made to the Terms, we will notify of such changes such as changing the "updated" date on these terms. Your continued use of our services following the changes or modifications will confirm your acceptance of such changes or modifications. If you do not agree with any changes or modifications, you must stop using our services immediately.<BR><BR>If you have any questions, comments or concerns regarding the Terms, please contact us at Officials@HFSHC.com.</p><BR>

<b>Article I: Age Restrictions</b><br>
<ul>(a) All participants must be 18 years of age or older to access or use any HFSHC.COM services.</ul><br>

<b>Article II: Conduct Responsibility</b><br>
<ul>(a) All participants are expected to act in a manner which is acceptable to the general public at all times. This includes, but is not limited to, obeying language restrictions listed in Article II (b), consucting oneself in a manner that is respectful to all members & staff, and not disturbing the general well being of the "club" atmosphere.<br>
<ul>(1) You may not post, utalize, store, transmit or participate in activities which that information is unlawful, defamitory, obscene, fradulent, harassing, threatening, hateful or spiteful to any person/the privacy of any person/the rights of any person.<BR>(2) You may not post, utalize, store, transmit or participate in activities that uses information to cheat (which includes but is not limited to transferring content between multiple accounts, transferring in-game curriencies between multiple accounts or exploiting bugs to a users advantage).<BR>(3) You may not sell, trade, share or giveaway your account at HFSHC.com<BR>(4) You may not Advertise for other games, websites, products or services (which includes but is not limited to posting referral links to other websites). </ul><BR>
(b) Language restrictions are to be strictly followed. Use of any words deemed unacceptable is forbidden and grounds for removal from the club. Restrictions apply to all areas of HFSHC.COM and all ways in which interaction with other HFSHC.COM members occurs, from the Community Center to private messages either on HFSHC.COM or other venues.<BR><BR>
(c) "SPAM", Harassment and "Chain" Mail
Email addresses, private messenger contacts and other personal information obtained for use with HFSHC.COM services may not be used to send "SPAM", harrassment messages or "Chain" mail unless user has given explicit consent for use.<BR><BR>
(d) You are agreeing that you will be solely responsible for your conduct while using our services.<BR><BR>
(e) You will use our services only for their intented purposes. You may not participate in the following..<BR>
<ul>(1) Use our services in any manner that would interfere with, disrupt, negatively affect or inhibit other users from fully enjoying our servies.<BR>(2) Use our services to damage, disable, overburden or impair the functionability of our servies.<BR>(3) Violate any applicable federal, state, local or international law or regulation with our services.<BR>(4) Copy, reproduce, distribute, perform or display any or all of our services, with the only exception being when you are granted written permission to do so by HFSHC.COM.<BR>(5) Use any kind of data mining, robots or any form of data gathering or extraction methods designed to take data from our services.<BR>(6). Design, develop or use any applications that interact with our servies that have not been provided by HFSHC.com or without written permission & an agreement to do so by HFSHC.com.<BR>(7) Use our services to engage in, encourage or promote illegal activity.<BR>(8) Introduce viruses, Torjan horses, worms, logic bombs and/or any other material that is either malicious or technologically harmful.<BR>(9) Attempt to gain unauthorized access to, interfere with, cause damage to or disrupt any part of our services, the server in which the services are stored, or any server, computer or database in connection with our services or users.</ul><BR>
(f) You will comply with all applicable laws and legal oligations, including but not limited to: copyright, trademark and all other intellectual property laws, libel, slander, defamation, trade libel, product disparagement, harassment, invasion of privacy, tort, obscenity, indecency, and copyright or trademark infringement. Violations of applicable laws may give rise to civil and/or criminal prosecution and penalties.<BR><BR>
(g) You agree not to access or use the Services in an unlawful way or for an unlawful or illegitimate purpose or in any manner that contravenes these terms. You further agree that you are solely responsible for your conduct while accessing or using our Services.<BR><BR>
(h) Notwithstanding anything to the contrary included in these Terms, we may at any time, with or without notice, suspend or terminate your access to some or all of the Services and refuse any and all current or future use of the Services at any time.<BR><BR>
(i) Additionally you agree to follow all Game Rules.</ul><BR>

<B>Article III: Privacy Policy</B><BR>
<ul>(a) While HFSHC.COM does not provide any guarantee that information submitted is secure from prying eyes, we do not sell or distribute any information gathered outside of HFSHC.com purposes unless otherwise stated by the user. Every member should expect to use his/her email address to participate in various club activities organized by other members, and a valid email address must be supplied to complete the joining process.</ul><BR>

<B>Article IV: Accessing Services & Account Security</B><BR>
<ul>(a) We may withdraw or amend the Services, and any related service or content, or restrict access (including by means of cancellation, termination, modification, or suspension of a user account) to all or certain users (including you) without notice and without liability to you in our reasonable discretion. Additionally, due to your geographic location, the Services or some of our features, services, or content may be unavailable to you. Notwithstanding anything to the contrary herein, we may terminate or suspend access to the Services based on your breach of these Terms.<BR><BR>
(b) To access certain Services on the hfshc.com server, you will be asked to provide registration details or other information, and in order to use such resources, all the information you provide must be correct, current, and complete. If you choose, or are provided with, a login ID, password, or any other piece of information as part of our security procedures, you must treat such information as confidential (other than username), and you must not disclose it to others.<BR><BR>
(c) You must notify hfshc.com for any unauthorized use of your login or any other breach of security. You should use caution when accessing your account from public or a shared computer so that others are not able to view or record your personal information. You can only access our Services through your own account. The gifting of, selling of or otherwise transferring your account is prohibited.<BR><BR>
(d) We reserve the right to automatically delete accounts after a period of inactivity.<BR><ul>
(1) Free to Play accounts will be deleted after a period of 6 months of inactivity (180 days).<BR>
(2) Subscriber accounts will be deleted after a period of 12 months of inactivity (360 days).</ul><BR>
(e) Each user may only have one account, period. Multiple accounts are prohibited and can result in the loss of all accounts associated with each other. No refunds will be given in cases of this type of breach.</ul><BR>

<B>Article V: Intellectual Property Ownership</B><BR>
<ul>(a) Our Services (including the text, graphics, images, photographs, videos, illustrations, information, data, software, coding and any other content and materials contained therein) is owned by HFSHC.com or our licensors and protected under both United States and foreign laws. Except as explicitly stated in these Terms, all rights in and to our Services are reserved by us or our licensors. Subject to your compliance with these Terms, you are granted a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to access and use the Services for non-commercial purposes. Any other access, use, copying, distribution, retransmission or modification of our Services, without our prior written permission, is strictly prohibited and will terminate the license granted herein and violate our intellectual property rights.<BR><BR>
(b) HFSHC.com, it's logo and all related names, logos, products and service names, designs and slogans are trademarks of HFSHC.com or its affiliates or licensors. You agree to not use such marks without the prior written permission of HFSHC.com. All other names, logos, products, service names, designs and/or slogans on the Services are the trademarks of their respective owners.<BR><BR>
(c) The services contain forums, networks, clubs and other interactive features that allow you to post, submit, publish, display or transmist to HFSHC.com and other users ("Post") content or materials ("User Contributions") on or through the Services. All User Contributions must comply with the following content standards;<BR><ul>
	(1) User Contributions must not be illegal, fraudulent, deceptive, obscene, threatening, defamatory, invasive of privacy, infringing of intellectual property rights, or otherwise injurious to third parties or objectionable, and must not consist of or contain software viruses, commercial solicitation, chain letters, mass mailings, or any form of "spam".<BR>
	(2) Any User Contribution that you Post will be considered non-confidential and non-proprietary, and you grant HFSHC.com a nonexclusive, royalty-free, perpetual, irrevocable, and fully sublicensable right to use, copy, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such User Contribution throughout the world in any media; however, HFSHC.com will only share personal information that you provide in accordance with our Privacy Policy.<BR>
	(3) You represent and warrant that you own or otherwise control all of the rights to the User Contributions that you Post at the time of Posting; that the User Contributions are accurate and not fraudulent or deceptive; and that the User Contributions do not violate these Terms or the rights (intellectual property rights or otherwise) of any third party, and will not cause injury to any person or entity. You understand that your User Contributions may be copied by other Services users and discussed on and outside of the Services, and if you do not have the right to submit User Contributions for such use, it may subject you to liability. HFSHC.com takes no responsibility and assumes no liability for any content Posted by you or any third party.<BR>
	(4) HFSHC.com has the right, but not the obligation, to monitor and edit or remove any User Contributions. HFSHC.com also has the right to terminate your access to all or part of the Services for any or no reason, including without limitation, any violation of these Terms. HFSHC.com may exercise these rights at any time, without notice or liability to you or any third party.</ul></ul>

<B>Article VI: Virtual Content</B><BR>
<ul>(a) Virtual Content is a generic term for the non-tangible products and services available to users for purchase within the Services which may be used within the Service to access certain features, functions, and other Virtual Content. Virtual Content includes but is not limited to, upgraded accounts and virtual items. Certain features in the Services may be unavailable if not purchased.<BR><BR>
(b) There are cases where you are permitted to use "real world" currency to purchase Virtual Content.<BR><BR>
(c) We may, at our sole discretion, provide opportunities for users to acquire certain Virtual Content free of charge, at reduced rates, or as bonus content when you acquire other Virtual Content. You may only acquire Virtual Content in the amount and at times permitted by us in our sole discretion and may only purchase Virtual Content for your personal use within the Services. All features, content, capabilities, and specifications of Virtual Content described or depicted in the Services are subject to change at any time without notice.<BR><BR>
(d) Virtual Content does not have monetary value, and may not be redeemed for legal currency, services, or items of value outside of the Services. Virtual Content obtained via the Services is provided to you under a limited, personal, revocable, non-transferable, non-sublicenseable license to use within the Services. You have no property interest; right or title in or to any Virtual Content appearing or originating in the service, and Virtual Content may not be transferred or resold in any manner not explicitly permitted by us. We may terminate your license to Virtual Content at any time and at our sole discretion.</ul><BR>

<B>Article VII: Purchases & Billing</B><BR>
<ul>(a) For all charges for any Virtual Content sold on the Services, we, or a payment processor acting on our behalf, will bill your credit card or alternative payment method. All prices for Virtual Content are displayed excluding taxes. You agree to pay all fees and applicable taxes incurred by you or anyone using an account registered to you. In the event that your credit card or alternative payment provider refuses to pay us for an amount credited to your account, we will have the right to delete the Virtual Content or the products or services purchased with such Virtual Content from your account. You agree that you will not cancel or reverse any charges for such Virtual Content or otherwise attempt to defraud us. In the event legal action is necessary to collect on balances due, you agree to reimburse us for all expenses incurred to recover sums due, including attorneys' fees and other legal expenses.<BR><BR>
(b) Any and all purchases of Virtual Content are non-returnable and non-refundable. If you redeem in-game currency to purchase in-game virtual items, you lose any statutory right of withdrawal because we begin performing our services upon your redemption of in-game currency for Virtual Content. If through some problem with your account or any other reason you lose Virtual Content and we can verify that you had it, we will make commercially reasonable efforts to replace them.<BR><BR>
(c) You will not receive any form of compensation for unused Virtual Content when an account is removed or closed. Certain jurisdictions may provide additional statutory rights, including a Cooling-Off Period which allows you to withdraw from a purchase. Nothing herein is meant to limit your return or cancellation rights for your purchase of Virtual Content under local law.</ul><BR>

<B>Article VIII: Third Party Content</B><BR>
<ul>(a) HFSHC.com may, at our sole discretion, provide information about third part products, services, activities or events in our Services, or we may allow third parties to make their content and information available on our Services. Your correspondence with third parties and your use of or interaction with any third party content are solely between you and the third party. HFSHC.com does not control, endorse, or adopt any third party content and make no representation or warranties of any kind regarding Third-Party Content, and your access to and use of such Third-Party Content is at your own risk. We are not responsible, or liable to you or any third party, for the content or accuracy of any materials provided by any third parties.</ul><BR>

<B>Article IX: Additional Terms</B><BR>
<ul>(a) Information Reliance<BR><ul>(1) The information presented on or through the Services is made available solely for general information purposes. We do not warrant the accuracy, completeness, or usefulness of this information. Any reliance you place on such information is strictly at your own risk. We disclaim all liability and responsibility arising from any reliance placed on such materials by you or any other visitor to the Services, or by anyone who may be informed of any of its contents.</ul><BR>
(b) Copyright Policy<BR>
<ul>(1) In accordance with the Digital Millennium Copyright Act and other applicable law, we have adopted a policy of terminating, in appropriate circumstances, the accounts of users who repeatedly infringe the intellectual property rights of others. If you believe that any part of our Services infringes any copyright that you own or control please review our DMCA Policy located Here.</ul><BR>
(c) Indemnification<BR><ul>
(1) To the fullest extent permitted by applicable law, you will defend, indemnify and hold harmless HFSHC.com, our committee, moderators, officers, directors, agents, partners, employees, independent contractors, service providers and consultants, and their respective directors, employees and agents (individually and collectively, the "HFSHC.com Parties"), from and against any losses, claims, damages, demands, costs, liabilities and expenses ("Claims") arising out of or related to (a) your access to or use of our Services; (b) your Feedback; (c) your violation of these Terms; (d) your violation, misappropriation or infringement of any rights of another (including intellectual property rights or privacy rights); or (e) your conduct in connection with our Services. You agree to promptly notify the HFSHC.com Parties of any third-party Claims, cooperate with the HFSHC.com Parties in defending such Claims, and pay all fees, costs and expenses associated with defending such Claims (including, but not limited to, attorneys’ fees). You also agree that the HFSHC.com Parties will have control of the defense or settlement, at our sole option, of any third-party Claims. This indemnity is in addition to, and not in lieu of, any other indemnities set forth in a written agreement between you and the HFSHC.com Parties.</ul></ul><BR>

THE SERVICES AND ALL CONTENT THEREIN ARE PROVIDED ON AN "AS IS" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF TITLE OR IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. BY USING THE SERVICE, YOUR ACKNOWLEDGE THAT YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK, THAT YOU ASSUME FULL RESPONSIBILITY FOR ALL COSTS ASSOCIATED WITH ALL SERVICING OR REPAIRS OF ANY EQUIPMENT YOU USE IN CONNECTION WITH YOUR USE OF OUR SERVICE, AND THAT NEITHER HFSHC.COM NOR ANY OF ITS AFFILIATES OR THEIR RESPECTIVE AGENTS, DIRECTORS, EMPLOYEES, INFORMATION PROVIDERS, LICENSORS, LICENSEES, OFFICERS AND/OR AFFILIATES WILL BE LIABLE FOR ANY DAMAGES OF ANY KIND RELATED TO YOUR USE OF THIS SERVICE.<BR><BR>
UNDER NO CIRCUMSTANCES, INCLUDING BUT NOT LIMITED TO HFSHC.COM NEGLIGENCE, WILL HFSHC.COM OR ANY OF ITS AFFILIATES OR THEIR RESPECTIVE AGENTS, DIRECTORS, EMPLOYEES, INFORMATION PROVIDERS, LICENSORS, LICENSEES, OFFICERS AND/OR AFFILIATES BE LIABLE FOR ANY CONSEQUENTIAL, DIRECT, INCIDENTAL, INDIRECT, PUNITIVE, OR SPECIAL DAMAGES RELATED TO (A) THE USE OF, (B) THE INABILITY TO USE, OR (C) ERRORS OR OMISSIONS IN THE CONTENTS AND FUNCTIONS OF THESE SERVICES, EVEN IF HFSHC.COM OR AN AUTHORIZED REPRESENTATIVE THEREOF HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. IN NO EVENT WILL THE TOTAL LIABILITY OF HFSHC.COM AND ITS AFFILIATES AND THEIR RESPECTIVE AGENTS, DIRECTORS, EMPLOYEES, INFORMATION PROVIDERS, LICENSORS, LICENSEES, OFFICERS AND/OR AFFILIATES TO YOU FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION (WHETHER IN CONTRACT OR TORT) EXCEED $50.00.<BR><BR>
YOU UNDERSTAND THAT THE WARRANTY DISCLAIMERS AND LIABILITY AND REMEDY LIMITATIONS LISTED ABOVE ARE A CONDITION OF US MAKING THE SERVICE AVAILABLE TO YOU. WITHOUT THEM, WE WOULD NOT AND COULD NOT MAKE THE SERVICES AVAILABLE. You accept that if we discover that you have violated any portion of these Terms, we may take any step we deem appropriate including but not limited to terminating your account and access to the Services. You acknowledge that if that happens, you will not receive any reimbursement or other compensation for any items that may be associated with your account at the time of termination.<BR><BR>
We reserve the right to modify our Services or to suspend or stop providing all or portions of our Services at any time. You also have the right to stop using our Services at any time. We are not responsible for any loss or harm related to your inability to access or use our Services.<BR><BR>
Governing Law and Venue. Any dispute arising from these Terms and your use of our Services will be governed by and construed and enforced in accordance with the laws of the State of Georgia, except to the extent preempted by U.S. federal law, without regard to conflict of law rules or principles (whether of Georgia or any other jurisdiction) that would cause the application of the laws of any other jurisdiction. You agree that any action at law or in equity arising out of or relating to these Terms will be filed only in the State courts located in Lake County, Montana, or in the Federal courts located in Missoula County, Montana, and you hereby irrevocably and unconditionally consent and submit to the exclusive jurisdiction of such courts over any suit, action or proceeding arising out of these Terms.
<BR><BR>Our failure to exercise or enforce any right or provision of these Terms will not operate as a waiver of such right or provision. If any provision of these Terms is held to be invalid, illegal, or unenforceable, the validity, legality, and enforceability of any such provision in every other respect and the remaining provisions of these Terms will be unimpaired and these Terms will continue in full force and effect, unless the provisions held invalid, illegal, or unenforceable will substantially impair the benefits of the remaining provisions hereof. The section titles in these Terms are for convenience only and have no legal or contractual effect. Except as otherwise provided herein, these Terms are intended solely for the benefit of the parties and are not intended to confer third-party beneficiary rights on any other person or entity. Notwithstanding anything to the contrary in these Terms, HFSHC.com may assign, transfer, and delegate these Terms and its obligations hereunder at any time, in its sole discretion. Termination of these Terms will not affect the provisions that, by their nature, are intended to survive the termination hereof. You agree that communications and transactions between you and HFSHC.com may be conducted electronically.
<BR><BR>
TERMS INCORPORATED BY REFERENCE. IF YOU DO NOT AGREE TO THESE TERMS OF USE, DO NOT ACCESS OR USE OUR SERVICES.


        </div>
      </div> <!-- /.row -->



<br/>
    </div>
    <!-- /.container -->
